module.exports = {
    COMMUNITY_CHAT : "COMMUNITY_CHAT",
    USER_CONNECTED : "USER_CONNECTED",
    NEW_USER_JOINED : "NEW_USER_JOINED",
    USER_DISCONNECTED: "USER_DISCONNECTED",
    MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
    MESSAGE_SENT: "MESSAGE_SENT",
    TYPING: "TYPING",
    VERIFY_USER : "VERIFY_USER",
    LOGOUT : "LOGOUT",
    NOTIFICATION : "NOTIFICATION",
};