// CHAT RELATED ACTIONS
export const ADD_CHAT_MESSAGE = 'ADD_CHAT_MESSAGE';
export const SET_SOCKET = 'SET_SOCKET';
export const LOGOUT_FROM_CHAT = 'LOGOUT_FROM_CHAT';
export const ADD_USER_TO_CHAT = 'ADD_USER_TO_CHAT';
export const UPDATE_TYPING_IN_CHAT = 'UPDATE_TYPING_IN_CHAT';
export const SET_MESSAGES = 'SET_MESSAGES';
export const SET_USERLIST = 'SET_USERLIST';
export const NOTIFY_NEW_USER = 'NOTIFY_NEW_USER';
export const CLEAR_NEW_USERS = 'CLEAR_NEW_USERS';


// USER RELATED ACTIONS
export const SET_USER   = 'SET_USER';
export const SET_ACTIVE_CHAT = 'SET_ACTIVE_CHAT';